# Generated by Django 4.2.4 on 2023-08-17 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
