# Generated by Django 4.2.4 on 2023-08-19 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_cart_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
    ]
