# Generated by Django 4.2.4 on 2023-08-21 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_carti'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
