# Generated by Django 4.2.4 on 2023-08-25 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_order_delete_carti'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
