# Generated by Django 4.2.4 on 2023-08-25 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='checkout',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.DeleteModel(
            name='Checkout',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
