# Generated by Django 4.2.4 on 2023-08-26 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_rupess',
            field=models.IntegerField(default=0),
        ),
    ]
